# docker-compose.yml
services:
  timescaledb:
    image: timescale/timescaledb-ha:pg17
    container_name: timescale-validator
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: validator_timescale
    volumes:
      - timescale-data:/var/lib/postgresql/data

volumes:
  timescale-data:
