# docker-compose.yml
services:
  timescaledb:
    image: timescale/timescaledb-ha:pg17
    container_name: timescale-validator
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ckigZDyic2PqXLcSyFlnOuBusvuwctRReXzxZrZd07Rcz14hDD
      POSTGRES_DB: validator_timescale
    volumes:
      - postgres-data:/home/postgres/pgdata/data

volumes:
  postgres-data:
